### ISSUE TITLE
Alternating Horus V2 frequencies

### ISSUE THREAD

**Issue by PC9DB** [Nevvman18/rs41-nfw#14]
Hello,

It would be a nice feature if the software would allow for two Horus V2 frequencies to be programmed which are used both during flight.
For example every odd minute a transmission on 434.714MHz and every even minute a transmission on 437.600MHz.

By using two frequencies, the number of receiving ground stations is improved.

Thank you in advance!

Best regards,
Mark de PC9DB

**Comment by Nevvman18** [comment]
Of course I can do that, thanks

**Comment by PC9DB** [comment]
Thank you very much.

Best regards,
Mark PC9DB

**Comment by Nevvman18** [comment]
I have already successfully implemented it, with additional repeat counter and adjustable additional delay to have a more customizable Horus telemetry. I will drop an update before the end of this month, but I have to clean up the code a little bit. This update will bring, besides that, also full APRS reporting and GPS restart watchdog in case of interference.

Franek

**Comment by whallmann** [comment]
Hey Franek,

good work. These additional options will help much. Thanks

cu Wolf


Franek ***@***.***> schrieb am Mi., 11. Dez. 2024, 20:29:

**Comment by Nevvman18** [comment]
Here are the new updates with the mentioned features:
https://github.com/Nevvman18/rs41-nfw/releases/tag/v31
https://github.com/Nevvman18/rs41-nfw/releases/tag/v32

Merry Christmas!

**Comment by PC9DB** [comment]
Excellent!!! Thanks.
